server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
      loadbalancer:
          retry:
            enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka