server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka