server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

    loadbalancer:
      health-check:
        enabled: true
      retry:
        enabled: true

eureka:
  server:
    # How often the eviction task runs (ms)
    eviction-interval-timer-in-ms: 5000 
    # Enable eviction
    enable-self-preservation: false 
  client:
    enable-self-preservation: false
    register-with-eureka: false
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka