server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres-product:5432/productdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/