server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5432/userdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: user-service