server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5432/userdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: user-service

  eureka:
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${random.value}

    client:
      registry-fetch-interval-seconds: 5

    instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10